language: ruby
cache: bundler
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
sudo: false
gemfile: Gemfile
script: bundle exec rspec spec
before_install:
  - gem update --system 3.1.2 --no-document
  - gem install bundler -v 2.1.2 --no-document
